---
title: "beepboop"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(tmap)
library(sf)
```


```{r}
#read in data for shiny app
cruise_pulse <- read_csv(here("data", "cruise_pulse_all_info.csv")) %>% clean_names()

reef_area <- read_csv(here("data", "reef_area_exposure.csv")) %>% clean_names()

seagrass_area <- read_csv(here("data", "seagrass_area_exposure.csv")) %>% clean_names()

basins <- read_csv(here("data", "basins_admin.csv")) %>% clean_names() 

watersheds <- read_csv(here("data", "top_20_watersheds.csv")) %>% clean_names()

reef_admin <- read_csv(here("data", "reef_admin.csv")) %>% clean_names()

basins <- read_csv(here("data", "basins_admin.csv")) %>% clean_names()

basins_long <- basins %>% pivot_longer(res_n_n_24_15:lvstc_n_n_24_15, names_to = "source", values_to = "n_quantity")
```

```{r}
 top_watershed_sf <- read_sf(here('data/spatial/top_20_watersheds.shp'))

reef_sf <-
  read_sf(here('data/spatial/reef_admin.shp'))

seagrass_sf <-
  read_sf(here('data/spatial/seagrass_admin.shp'))

basins_sf <-
  read_sf(here('data/spatial/basins_admin.shp'))

top_watershed_df <- top_watershed_sf %>% 
  as.data.frame() %>% 
  select(-geometry)

basins_df <- basins_sf %>% 
  as.data.frame() %>% 
  select(-geometry)

seagrass_df <- seagrass_sf %>% 
  as.data.frame() %>% 
  select(-geometry)

reef_df <- reef_sf %>% 
  as.data.frame() %>% 
  select(-geometry)

head(top_watershed_df)
head(basins_df)
head(seagrass_df)
head(reef_df)

ggplot() +
 # geom_sf(data = top_watershed_sf) +
  geom_sf(data = reef_sf) +
  geom_sf(data = seagrass_sf) +
  geom_sf(data = basins_sf, aes(fill = lvstc_N)) +
  theme_minimal()
```
 
```{r}
 basins_long_graph <- basins_long %>% 
  group_by(admn_bn_c_80, source, country_c_80) %>%
  summarize(n_total = sum(n_quantity))
```
 
```{r}
reef_admin_edit <- reef_admin %>% 
  group_by(name_c_80, country_c_80) %>% 
  summarize(n_area_total = sum(area_km2_n_24_15))
```


 